M48
; DRILL file {KiCad 8.0.5} date 2025-10-14T02:48:24+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-14T02:48:24+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X165.0Y-75.0
X165.0Y-115.0
X205.0Y-75.0
X205.0Y-115.0
M30
